#mailer post request
POST http://localhost:3200/users/subscribe
Content-Type: application/json

{
    "name": "Kelechi",
    "email": "kelechiorunta1@gmail.com"
}

###
GET http://localhost:3200/users/unsubscribe/Kelechi

###
POST http://localhost:3200/users/login
Content-Type: application/json

{
    "name": "Kelechi",
    "password": "kelechiorunta1@gmail.com"
}