#mailer post request
POST http://localhost:3200/users/subscribe
Content-Type: application/json

{
    "name": "Kelechi",
    "email": "kelechiorunta1@gmail.com",
    "password": "keleman4xst"
}

###
GET http://localhost:3200/users/unsubscribe/Kelechi

###
GET http://localhost:3200/users/session
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZDU2MzNkMDM2MmY3NGJjZjFhODY1MiIsIm5hbWUiOiJLZWxlY2hpIiwiaWF0IjoxNzQyMDM5Mjc5LCJleHAiOjE3NDIwNDI4Nzl9.BDelcUaUZ_9z3LxozGz3zcUgxhptFwXpjLYxizes_L4

###
POST http://localhost:3200/users/login
Content-Type: application/json

{
    "name": "Kelechi",
    "password": "keleman4xst"
}

###
POST http://localhost:3200/users/signup
Content-Type: application/json

{
    "name": "Enyinnaya",
    "email": "oruntakelechi86@gmail.com",
    "password": "keleman4xst"
}

###
GET http://localhost:3200/users/logout